# Generated by Django 3.0.2 on 2020-01-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_name', models.CharField(max_length=50)),
                ('type_reporter', models.CharField(max_length=10)),
                ('date_reported', models.DateField()),
                ('Time_reported', models.TimeField()),
                ('name_repoter', models.CharField(max_length=100)),
                ('address_repoter', models.TextField()),
                ('date_crime', models.DateField()),
                ('time_crime', models.TimeField()),
                ('place_offence', models.TextField()),
                ('landmark', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
