# Generated by Django 3.0.2 on 2020-01-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_remove_dbtable_landmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbtable',
            name='type_reporter',
        ),
        migrations.AddField(
            model_name='dbtable',
            name='email_reporter',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='dbtable',
            name='phone_reporter',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='dbtable',
            name='Time_reported',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dbtable',
            name='date_reported',
            field=models.TextField(),
        ),
    ]
