# Generated by Django 3.0.2 on 2020-01-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_auto_20200127_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbtable',
            name='crime_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dbtable',
            name='date_crime',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dbtable',
            name='name_repoter',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dbtable',
            name='time_crime',
            field=models.TextField(),
        ),
    ]
