# Generated by Django 3.0.2 on 2020-01-27 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_auto_20200127_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbtable',
            old_name='address_repoter',
            new_name='address_reporter',
        ),
    ]
