# Generated by Django 3.0.2 on 2020-01-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_auto_20200127_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbtable',
            name='Time_reported',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dbtable',
            name='crime_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dbtable',
            name='date_crime',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dbtable',
            name='date_reported',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dbtable',
            name='name_reporter',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dbtable',
            name='phone_reporter',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dbtable',
            name='time_crime',
            field=models.TextField(),
        ),
    ]
